### PR TITLE
WeBWorK: build representations using local PG repository

### PR DESCRIPTION
**Pull request by Alex-Jordan**
Since I accidentally rebased #2542 on #2541, I can go ahead and open this PR as well. This is built on top of both of those.

This lets you put a clone of PG on your local system and use that to build the static representations instead of a WW server. For me it reduces the sample chapter representations build time from 36 seconds to 19 seconds. And I think the proportional improvement is even better than that sounds. The latex-image images in the sample chapter take a large chunk of that time either way, and if you remove those, it's about 30 seconds down to 13. I'll be curious to hear how much this speeds up APEX representation builds for @sean-fitzpatrick. I haven't tried it yet myself with ORCCA.

For this to work, you have to set `static-processing="local"` in the publisher file.

And of course, you have to get the PG repository on your system (version 2.19 or later), along with the perl dependencies. The instructions for doing this are added to `doc/guide/publisher/webwork.xml` here. So you would follow those instructions to try it out. I may need feedback about those instructions, because my own system is not "virgin" and maybe already had things on it that I'm not aware will need to be installed on a typical machine.

This separates one of three main things from the big Tacoma PR. (The other two are using local .pg files, and support for using a remote version 2.19 webwork2 server.) I did not want to separate this earlier, because untangling this feature from the other two meant I needed to rewrite all of the bits for this in `pretext.py` that Glenn, Drew, and I did last year. However, the recent thing that happened where I renamed `coursepassword` to `password` (and how that caused a problem for using old representations files with a new HTML build) got me thinking I would have to do a rewrite anyway. So here it is! And after this can come those other two main features from Tacoma.

### CODE REVIEW

**Comment by Alex-Jordan** [comment]
A note for Rob: you will see a nontrivial diff with the representations file using this, compared with using the webwork-ptx server. That will come from how this uses PG 2.19 and the webwork-ptx server is still 2.17. There are things like attributes written in a different order for some reason. That's just some consequence of PG's evolution. And there are other differences too like how certain multiple choice output comes back.

**Comment by sean-fitzpatrick** [comment]
OK, the first thing I would add to the documentation would be advice on setting the `$pg-root` environment variable.
Right now one might get the mistaken impression that it's enough to set `directories: root: /opt/webwork/pg`, but `$pg-root` shows up many times in the config file.

It would be easier/faster to ensure `$pg-root` is defined than to replace this with `/opt/webwork/pg` a dozen times or more.

**Comment by sean-fitzpatrick** [comment]
Another detail that likely needs a reminder: the WW macros file that you generate from your book (with the contents of `latex-image-preamble`) will need to be placed in `/opt/webwork/pg/macros`

**Comment by sean-fitzpatrick** [comment]
I guess I just assumed it would be needed! Just as I started it, it occurred to me that i might need the `APEX.pl` file so I dropped it in.

**Comment by Alex-Jordan** [comment]
If this works, and you continue to use `pretext/pretext/pretext` to make the PDF (instead of the CLI) then it may resolve the issue you reported earlier with the layout of multiple choice options. But you'd have to wait until #2542 makes its way to the CLI before you could then use the representations file from today while returning to the CLI for the HTML and PDF builds. If that makes sense.

> Sorry, spoke too soon. extract-pg.xsl runs, then pretext-pg-macros.xsl.

I guess the slowness may be from re-building the entire book's XML tree for the sake of making the macros when that's redundant work if you already built it for the exercises. I'll look at that today.

**Comment by rbeezer** [comment]
> Since I accidentally rebased https://github.com/PreTeXtBook/pretext/pull/2542 on https://github.com/PreTeXtBook/pretext/pull/2541, I can go ahead and open this PR as well.

I don't want to be unraveling all of this.  Plesse don't build further off of accidents.

**Comment by sean-fitzpatrick** [comment]
Looks like you can get this from `libyaml-libyaml-perl`

**Comment by Alex-Jordan** [comment]
> I don't want to be unraveling all of this. Plesse don't build further off of accidents.

But if you process #2541, I would rebase #2542 (as well as this here). And then once #2542 is processed, I would rebase this one here. Where we are at has facilitated Sean being able to try this out, and he's discovering this and that (like perlk modules he needed to install but I didn't).

**Comment by Alex-Jordan** [comment]
I'll mark two of these PRs as draft.

**Comment by rbeezer** [comment]
Yes, please mark anything dependent as a draft and then roll off the draft status as I try to work thorough these.  I just sat down to continue (finish?) a WW review, but now my limited window for that has been spent trying to figure out which PR it was.

**Comment by sean-fitzpatrick** [comment]
`UUID::Tiny` can be installed with `libuuid-tiny-perl`
`Class::Tiny` can be installed with `libclass-tiny-perl`
`DBI` can be installed with `libdbi-perl`

I will install these and try again, but there may be other problems.

**Comment by Alex-Jordan** [comment]
Thanks, I will add those modules.

The error report looks like it is finding places where PG itself has sloppy code (like using `GD::gdTransparent` instead of `'GD::gdTransparent'`).  It doesn't come up when using a `webwork2` server because that workflow is more tolerant of sloppy perl. And it must be that APEX has an exercise that actually uses things with this sloppy perl, but the sample chapter does not.

So with the list of things in that error, there are some PG things to edit. I will make the case to the WW/PG team that they should be hotfixes to 2.19, so this can all work with 2.19, even though 2.20 is imminent. For now, you would either have to pause, or make some edits to your pg repo. They look like trivial edits. For example this error line:
```
Failed to evaluate module WWPlot: Bareword "GD::gdTransparent" not allowed while "strict subs" in use at /opt/webwork/pg/lib/WWPlot.pm line 376.
```
implies you would go to `/opt/webwork/pg/lib/WWPlot.pm` line 376, and change `GD::gdTransparent` to `'GD::gdTransparent'`.

**Comment by Alex-Jordan** [comment]
@sean-fitzpatrick I think you should pause until I work out these other perl errors. They are not as simple as I thought.

**Comment by sean-fitzpatrick** [comment]
I think it is failing on problems with TikZ images.

**Comment by sean-fitzpatrick** [comment]
I get one error right away:
`Compilation failed in require at (eval 141) line 1.`
But then it starts processing problems. It is definitely the graphical ones that fail. Here is a typical error.
I'll try again with GD installed to see if I still get it.
```
PTX:INFO    : building representations of PTX-authored WeBWorK problem
PTX:INFO    : sending webwork-ex-limit-intro-numerical-graphical-1 to socket to save in /home/sean/github/APEXCalculusPTX/generated-assets/webwork/webwork-representations.xml: origin is 'ptx'
Failed to generate png file. at [TMPL]/lib/LaTeXImage.pm line 311
   from within LaTeXImage::use_convert called at line 247 of [TMPL]/lib/LaTeXImage.pm
   from within LaTeXImage::draw called at line 596 of [TMPL]/lib/PGcore.pm
   from within PGcore::insertGraph called at line 1532 of [TMPL]/macros/PG.pl
   from within main::insertGraph called at line 1 of (eval 397)
   from within PGML::Eval called at line 950 of [TMPL]/macros/core/PGML.pl
   from within PGML::Parse::replaceCommand called at line 1444 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format::Command called at line 1267 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format::string called at line 1855 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format::ptx::Align called at line 1261 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format::string called at line 1248 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format::format called at line 1996 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format called at line 2009 of [TMPL]/macros/core/PGML.pl
   from within PGML::Format2 called at line 39 of 
PTX:INFO    : saving image file webwork-ex-limit-intro-numerical-graphical-1-image-1.tgz (contents) in /home/sean/github/APEXCalculusPTX/generated-assets/webwork/images
PTX:WARNING : /home/sean/github/APEXCalculusPTX/generated-assets/webwork/images/webwork-ex-limit-intro-numerical-graphical-1-image-1.tgz did not contain a .png file
```

All the errors are like this.

**Comment by Alex-Jordan** [comment]
In `pretext/pretext.cfg`, did you verify that the various "externalPrograms" executable paths are correct for your system? This looks like what I say before I updated them from the defaults to where my latex things are installed.

**Comment by sean-fitzpatrick** [comment]
I will double-check. One note regarding timing with `pretext/pretext`: it spends a couple of minutes on `pretext-ww-problem-sets.xsl`. And it seems to be doing `pretext-pg-macros.xsl` *twice*.

**Comment by Alex-Jordan** [comment]
On your last note. Each time `pretext.py` applies a stylesheet to the project source, there is a startup cost. Now I see that we are paying that startup cost three times (two of them being for building the problem sets and macros, both of which are needed for local PG processing). I will work on changing it so we don't pay 3x startup costs.

**Comment by sean-fitzpatrick** [comment]
OK... a roundup of replies:
- for external programs, tar was at `/usr/bin/tar` instead of `/bin/tar`. I changed that. The other paths match what I get from running, e.g., `which latex`. I am still getting errors on the problems with images
- other than that, I am now running without errors. Yay!
- Building WW reps took me 15 minutes with the CLI, and a bit over 16 minutes using local processing. So that isn't great.
- That said, most of the time is what you call startup costs. The actual processing of the problems is visibly faster. Using the server, I can watch them tick by one by one. Now they are flying by, with a brief pause at the ones with images.

**Comment by sean-fitzpatrick** [comment]
Aside from watching it with a stopwatch, I don't think I have a good way of getting timing for the different parts of the script. 

But I would guess that the actual processing of problems is less than 10% of the total time. Most of it is application of templates.

Image processing is still failing, but everything else works. I am pretty sure all the external application paths are set correctly.

**Comment by sean-fitzpatrick** [comment]
Ohhh... I think I see what is wrong. On a hunch, I tried manually running `convert foo.png foo.pdf` and I get:
```
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/426.
```
So I need to go edit the ImageMagick policy file.

**Comment by sean-fitzpatrick** [comment]
ImageMagick policy was the issue. I get a clean run now, except for a warning about using 'unquoted string "theta"' in one problem. That sounds like an authoring problem I can go fix.

I decided to go ahead and try manual timing. Without commenting anything out, running `time` on this gives me:
```
real    15m7.552s
user   11m25.671s
```

my timings on individual steps:

`extract_pg`:    3m15s
`pretext-ww-problem-sets`:    2m30s
`pretext-pg-macros`:    2m50s
`pretext-pg-macros` (second time): 3m05s
Actual processing of the problems: 3m40s

Now running with the lines listed above commented out (`extract-pg` and problem generation only).
The `time` command gives me:
```
real:    6m49s
user:    3m7s
```
That is pretty consistent with adding the times for extraction and processing above.
It is also less than half the time it takes to do server processing (this is usually about 15 minutes).

**Comment by Alex-Jordan** [comment]
OK, this is ready to review. First, some data:

- `make sample-chapter-representations`:
    - with AIM WW server: 39 seconds
    - with local PG: 19 seconds
- ORCCA (just part 1 of 3) representations build:
    - with AIM WW server: 20 min
    - with local PG: 12 min

A note: at this time, I cannot speed things up fully and remove certain redundancies that Sean noticed. Although I did get one significant redundancy removed. I think this is OK and optimization can come later. It's still a speedup for me as noted above.

For testing, what I did is:

- on master, build the sample chapter tex file and html output, and put it all in a folder.
- repeat with this branch, still using the AIM server to make representations.
- repeat with this branch, now using local PG to make representations. 

There is no diff (aside from dates) between the first two folders.

Between the latter two (this branch with AIM versus local PG), there are expected diffs given that the AIM server uses PG 2.17 and local PG is 2.19. Also some differences between the latex tools for image making on the WW server and my local latex tools.

Some of that diff includes XML attributes coming out in a different order. Other things are just part of how PG 2.19 is behaving differently from 2.17. There are around ten classes of diffs that appear, but they appear many times. So it is a bit tedious to examine the diffs. My routine is to run `diff -r this_folder that_folder > diff.txt` and then open `diff.txt` in an editor. Where I can use regex to remove lines in bulk where I understand the reason for the diff and can narrowly code it in a regex replacement.

Before you set out to test local PG processing, you will need to get local PG going on your machine. The publisher guide, webwork section, should have better guidance now thanks to @sean-fitzpatrick's guinea pigging. I'm sure you will want to review the guide changes too, but for convenience I posted the important page [here](https://spot.pcc.edu/~ajordan/temp/webwork-local-pg-static-processing.html) in case you want to start by seeing if you hit trouble getting PG running.

Lifting the draft status now.

**Comment by Alex-Jordan** [comment]
The script knows to still reach out to a webwork2 server if the problem is specified by a "source" attribute. Local PG processing can only happen if the problem is authored in PTX, or if the problem is a local problem (with path specified by a "local" attribute). (That last option has not yet made its way into a PR other than the big Tacoma one. It is slated for two PRs from now.)

All of this is just for generating static representations. Live rendering still needs a webwork2 server until we polish using the standalone renderer.

**Comment by rbeezer** [comment]
Seem to be dead in the water dealing with Perl.  First, mass install from long command in the Guide.  Finished with an error?
```
make[1]: Leaving directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
Manifying 2 pod documents
  TINITA/YAML-LibYAML-v0.904.0.tar.gz
  /usr/bin/make -- OK
Prepending blib/arch and blib/lib of 20 build dirs to PERL5LIB, reaching size 2095; for 'test'
The current configuration of allow_installing_outdated_dists is 'ask/yes', but for this option we would need 'CPAN::DistnameInfo' installed. Please install 'CPAN::DistnameInfo' as soon as possible. As long as we are not equipped with 'CPAN::DistnameInfo' this option does not take effect
Running make test for TINITA/YAML-LibYAML-v0.904.0.tar.gz
make[1]: Entering directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- LibYAML.bs ../blib/arch/auto/YAML/XS/LibYAML/LibYAML.bs 644
Manifying 1 pod document
make[1]: Leaving directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
make[1]: Entering directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- LibYAML.bs ../blib/arch/auto/YAML/XS/LibYAML/LibYAML.bs 644
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-I../blib/lib" "-I../blib/arch" test.pl
1..1
ok 1 - Tests for libyaml extension are all defined at the top level
make[1]: Leaving directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t t/oop/*.t
t/000-require-modules.t .. ok   
t/alias.t ................ ok     
t/api.t .................. ok     
t/ascii.t ................ ok   
t/author-pod-syntax.t .... skipped: these tests are for testing by the author
t/binary.t ............... ok   
t/blessed.t .............. ok     
t/boolean-boolean.t ...... skipped: boolean not installed
t/boolean-invalid.t ...... ok     
t/boolean-jsonpp.t ....... ok   
t/boolean.t .............. ok   
t/bug-pvf.t .............. ok   
t/bug-stack.t ............ ok   
t/code.t ................. ok   
t/dump-heuristics.t ...... ok   
t/dump-int.t ............. ok   
t/dump.t ................. ok   
t/duplicate-keys.t ....... ok   
t/empty.t ................ ok   
t/error.t ................ ok     
t/file.t ................. ok   
t/glob.t ................. ok   
t/indent.t ............... ok   
t/io-handle.t ............ ok   
t/leak.t ................. ok     
t/libyaml-version.t ...... # libyaml version = 0.2.4
t/libyaml-version.t ...... ok   
t/load-blessed.t ......... ok     
t/load.t ................. ok   
t/load_standard_tags.t ... ok     
t/loadfile-empty.t ....... ok   
t/long_plain_wrap.t ...... skipped: Failing test. Not yet implemented
t/magic.t ................ ok   
t/native.t ............... ok   
t/null.t ................. ok   
t/numbers.t .............. ok   
t/oop/10-basic.t ......... ok   
t/oop/11-schema.t ........ # inf: Inf -inf: -Inf nan: NaN
t/oop/11-schema.t ........ ok      
t/oop/12-alias.t ......... ok   
t/oop/13-utf8.t .......... ok   
t/path-class.t ........... ok   
t/pl_sv_undef.t .......... ok   
t/private.t .............. ok   
t/quote.t ................ ok   
t/ref-scalar.t ........... ok     
t/regexp.t ............... ok     
t/string_nulls.t ......... ok   
t/tags.t ................. ok   
t/tied.t ................. ok   
t/utf8.t ................. ok   
All tests successful.
Files=49, Tests=1497,  2 wallclock secs ( 0.07 usr  0.02 sys +  1.21 cusr  0.25 csys =  1.55 CPU)
Result: PASS
  TINITA/YAML-LibYAML-v0.904.0.tar.gz
  /usr/bin/make test -- OK
Running make install for TINITA/YAML-LibYAML-v0.904.0.tar.gz
Prepending blib/arch and blib/lib of 21 build dirs to PERL5LIB, reaching size 2206; for 'install'
make[1]: Entering directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- LibYAML.bs ../blib/arch/auto/YAML/XS/LibYAML/LibYAML.bs 644
Manifying 1 pod document
make[1]: Leaving directory '/home/rob/.cpan/build/YAML-LibYAML-v0.904.0-0/LibYAML'
Manifying 2 pod documents
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create '/usr/local/lib/x86_64-linux-gnu/perl/5.36.0/YAML'
mkdir /usr/local/lib/x86_64-linux-gnu: Permission denied at /usr/share/perl/5.36/ExtUtils/Install.pm line 470.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
make: *** [Makefile:824: pure_site_install] Error 13
  TINITA/YAML-LibYAML-v0.904.0.tar.gz
  /usr/bin/make install  -- NOT OK
```

Running locally, quickly get an error
```
PTX:INFO    : validating, cleaning server URL: https://webwork-ptx.aimath.org
Can't locate Mojo/Base.pm in @INC (you may need to install the Mojo::Base module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /home/rob/mathbook/mathbook/script/webwork/pg-ptx.pl line 3.
BEGIN failed--compilation aborted at /home/rob/mathbook/mathbook/script/webwork/pg-ptx.pl line 3.
```

Tried to install `Mojo::Base`
```
$ cpan Mojo::Base
Reading '/home/rob/.cpan/Metadata'
  Database was generated on Sun, 06 Jul 2025 13:29:02 GMT
CPAN: YAML loaded ok (v1.30)
Reading 51 yaml files from /home/rob/.cpan/build/
............................................................................DONE
Restored the state of 21 (in 0.0743 secs)
Running install for module 'Mojo::Base'
  SRI/Mojolicious-9.41.tar.gz
  Has already been unwrapped into directory /home/rob/.cpan/build/Mojolicious-9.41-0
  SRI/Mojolicious-9.41.tar.gz
  Has already been prepared
  SRI/Mojolicious-9.41.tar.gz
  Has already been made
  SRI/Mojolicious-9.41.tar.gz
  Has already been tested successfully
  SRI/Mojolicious-9.41.tar.gz
  Already tried without success
CPAN: CPAN::Meta loaded ok (v2.150010)
```
Is "tried without success" an error?  It didn't help in any event.

**Comment by sean-fitzpatrick** [comment]
Earlier in the comments I listed the libraries I found in the Pop_OS package manager if you want to install without cpanm.

Alex didn't list them in the guide since those packages may not exist in Linux distributions that are not based on Ubuntu. (Not to mention Mac or Windows.)

Since I didn't use cpanm I didn't run into these errors. (Not sure that's helpful...)

**Comment by rbeezer** [comment]
@sean-fitzpatrick - not on PopOS!  Debian on my desktop.

**Comment by rbeezer** [comment]
> These may be available from Linux package distributions, but the details differ from one flavor of Linux to the next. If you can sort out which packages based on the list of perl modules below, that is recommended.

No, I can't do this again.

**Comment by rbeezer** [comment]
Installed  Future::AsyncAwait.  Maybe over that hump.

Where did the instructions say to install as root?  How big a mess do I have in my personal directory now?

**Comment by sean-fitzpatrick** [comment]
The GD package is one of the ones that I identified when testing for Alex. It should be on his list of modules?

I think I ran into something like the last error due to ImageMagick permissions.

**Comment by rbeezer** [comment]
Log file on `GD::Image` install.

Problem near the end: "ExtUtils::PkgConfig requires the pkg-config utility,..."

```
cpanm (App::cpanminus) 1.7046 on perl 5.036000 built for x86_64-linux-gnu-thread-multi
Work directory is /root/.cpanm/work/1751847860.804412
You have make /usr/bin/make
You have LWP 6.68
You have /usr/bin/tar: tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
Searching GD::Image () on cpanmetadb ...
--> Working on GD::Image
Fetching http://www.cpan.org/authors/id/R/RU/RURBAN/GD-2.83.tar.gz
-> OK
Unpacking GD-2.83.tar.gz
Entering GD-2.83
Checking configure dependencies from META.json
Checking if you have ExtUtils::Constant 0.22 ... Yes (0.25)
Checking if you have File::Which 0 ... Yes (1.27)
Checking if you have ExtUtils::PkgConfig 0 ... No
==> Found dependencies: ExtUtils::PkgConfig
Searching ExtUtils::PkgConfig (0) on cpanmetadb ...
--> Working on ExtUtils::PkgConfig
Fetching http://www.cpan.org/authors/id/X/XA/XAOC/ExtUtils-PkgConfig-1.16.tar.gz
-> OK
Unpacking ExtUtils-PkgConfig-1.16.tar.gz
Entering ExtUtils-PkgConfig-1.16
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.64)
Configuring ExtUtils-PkgConfig-1.16
Running Makefile.PL
***
*** ExtUtils::PkgConfig requires the pkg-config utility, but it doesn't
*** seem to be in your PATH.  Is it correctly installed?
***  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
***
-> N/A
-> FAIL Configure failed for ExtUtils-PkgConfig-1.16. See /root/.cpanm/work/1751847860.804412/build.log for details.
-> FAIL Installing the dependencies failed: Module 'ExtUtils::PkgConfig' is not installed
-> FAIL Bailing out the installation for GD-2.83.
```

**Comment by sean-fitzpatrick** [comment]
I'm realizing now that there are gaps in my sleuthing for Alex, because I installed using .deb packages, and apt resolves dependencies automatically. 

It would appear that cpanm does not! 

For images I think the file is /etc/imagemagick/policy.xml and the permissions in the PDF line need to be changed to allow writing.

**Comment by Alex-Jordan** [comment]
I rebased off master and force pushed. Just giving a heads up. No changes to anything (yet).

**Comment by rbeezer** [comment]
I am going to merge this with what I have now.  I do not want to test again.  It needs to be split into multiple commits and I will do that.  Please wait for me to finish my end, and then you can finish this up.  Do not open any new WW PRs until that is done.

**Comment by Alex-Jordan** [comment]
I'll do as you say, but I was only going to try to improve the documentation. You and Sean ran into perl package installation issues and I got the impression the instructions aren't good enough for all flavors of Linux. I don't have a Linux OS I can play with, let alone all the flavors. But I was just going to try to edit it based on what you reported today.

**Comment by rbeezer** [comment]
> I'm trying to understand. 

When a PR is ready for review, I put a lot of work into testing it and preparing it to merge.  If then there is new work added during that process, then yes, I start all over testing **everything**.  Same with my own work.  That is how we avoid show-stopping bugs and can have rolling releases.

Why is all this work on one commit?  I'm going to have to do the work to bust it up, or test all over again after it is redone.  The former sounds easier to me right now.

You know the expectations for PRs.  If it is a draft, say so.  When it is ready for review, say so.  And if it is ready for review, it should be as close as ready-to-merge as you can make it.  If I **ask** fir changes, then I'm ready for that.  But don't force-push (or add new work) on your own while I'm reviewing and merging.  Don't ask for a review on the expectation you will have another go at it (resulting in a further comprehensive review).

**Comment by rbeezer** [comment]
OK, now 5 commits and merged.

Much faster, which should make @bnmnetp  and @sean-fitzpatrick  happy!

Who are we advertising this to?  Server admins?  Authors?  There's a lot to do to get this set up.

**Comment by sean-fitzpatrick** [comment]
Going through my comments near the top of the thread, here are the packages I installed to get this working. I think these should be available on any Debian-based system:
- `Locale::Maketext:Lexicon` can be installed with `liblocale-maketext-lexicon-perl`
- `TAML::XS` can be installed with `libyaml-libyaml-perl`
- `UUID::Tiny` can be installed with `libuuid-tiny-perl`
- `Class::Tiny` can be installed with `libclass-tiny-perl`
- `DBI` can be installed with `libdbi-perl`
- For the GD stuff I installed `libgd-perl` and `libgd-text-perl`

I think that's all of them. I had to change the config file to point to the correct location for `tar`, and update the `policy.xml` file.

**Comment by Alex-Jordan** [comment]
> It would appear that cpanm does not!

cpanm resolves dependencies as far as perl modules go. If perl module X depends on perl module Y, you will get both. But some of these perl modules are the interface between perl and some system tool, like gd. And cpanm won't install those kinds of dependencies.

**Comment by Alex-Jordan** [comment]
> Add webwork directory to top-level README and make a short one for script/webwork.

I'm not sure what this is asking for. What is "top-level README"? It sounds like a directory, but all instances of "README" that I find are `README.md` files. And the top-level such file is not structured for listing directories. Sorry, I just need clarification here.
